language: node_js

node_js:
 - "12"

before_script:
 - npm install

script:
 - npm test
 - echo "hello world"

# deploy:
# provider: heroku
# app: vuetube-react
# api_key:
#   secure: cd46f4d2-3a26-412c-8511-4f75ee6258cc
    